### ISSUE TITLE
Empty parameters are rejected even if pattern allows them

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client#331]
Test with `sdm-pack-spring` and empty package, which is legal:

```2018-08-03T06:50:31.494Z [m:44573:f5d481b5-9ba5-4d00-a048-ab84f6185e15:T5964N9B7:create-spring:079] [error] Failed invocation of command 'create-spring': {"name":"Error","message":"Parameter 'rootPackage' required but missing in invocation to 'create-spring'","stack":"Error: Parameter 'rootPackage' required but missing in invocation to 'create-spring'\n    at handler.parameters.forEach.p (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/server/AbstractAutomationServer.ts:48:27)\n    at Array.forEach (<anonymous>)\n    at BuildableAutomationServer.validateCommandInvocation (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/server/AbstractAutomationServer.ts:43:28)\n    at BuildableAutomationServer.invokeCommand (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/server/AbstractAutomationServer.ts:23:24)\n    at ExpressRequestProcessor.invokeCommand (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/internal/transport/AbstractRequestProcessor.ts:204:30)\n    at ses.run (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/internal/transport/AbstractRequestProcessor.ts:91:18)\n    at Namespace.run (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/continuation-local-storage/context.js:48:5)\n    at ExpressRequestProcessor.processCommand (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/internal/transport/AbstractRequestProcessor.ts:57:13)\n    at exp.post (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/internal/transport/express/ExpressServer.ts:174:30)\n    at Layer.handle [as handle_request] (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/route.js:137:13)\n    at ExpressServer.authenticate (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/src/internal/transport/express/ExpressServer.ts:299:17)\n    at Layer.handle [as handle_request] (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/route.js:137:13)\n    at cors (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:188:7)\n    at /Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:224:17\n    at originCallback (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:214:15)\n    at /Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:219:13\n    at optionsCallback (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:199:9)\n    at corsMiddleware (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/cors/lib/index.js:204:7)\n    at Layer.handle [as handle_request] (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:335:12)\n    at next (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:275:10)\n    at initialize (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/passport/lib/middleware/initialize.js:53:5)\n    at Layer.handle [as handle_request] (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:317:13)\n    at /Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:335:12)\n    at next (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/express/lib/router/index.js:275:10)\n    at internalNext (/Users/rodjohnson/sforzando-dev/idea-projects/sample-sdm/node_modules/helmet/index.js:45:33)"}
```

**Comment by ddgenome** [comment]
This might be the cause https://github.com/atomist/automation-client/blob/19cab247aa3f4f72849123859b5edb7f803fd8a3/lib/internal/parameterPopulation.ts#L38

**Comment by cdupuis** [comment]
This line is only for configuration values not for parameters.
