### ISSUE TITLE
Error when creating pull request under GitCommandGitProject

### ISSUE THREAD

**Issue by ddgenome** [atomist/automation-client#387]
User is seeing this error when trying to create a PR using `GitCommandGitProject.raisePullRequest`.

```
Running: git createBranch
Success: git createBranch
Committing and pushing version incrementing changes for OWNER/REPO
Running: git commit
Success: git commit
Running: git push
Success: git push
ERROR caught: name is not defined
ReferenceError: name is not defined
    at GitCommandGitProject.raisePullRequest (c:\Users\USER\Source\REPO\node_modules\@atomist\automation-client\lib\project\git\GitCommandGitProject.ts:185:59)
    at Object.versionIncrement (c:\Users\USER\Source\REPO\src\terraform\utils.ts:102:29)
```

**Comment by ddgenome** [comment]
Looks like the default value for the body points to the DOM name object, which is not defined in Node.js. I'm not sure why we include that library. I would guess the default is supposed to be `this.name`.
